config/routes.rb
Rails.application.routes.draw do
  resources :stocks
  devise_for :users
  # get 'home/index'
  root 'home#index'
  get 'home/about'
  post "/" => 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/stock.rb
class Stock < ApplicationRecord
    belongs_to :user
    validates :ticker, presence: true
    validates :ticker, format: {without: /\s/ }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
        has_many :stocks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @api = params[:ticker]
    if params[:ticker] == ""
      @nothing = "Please enter a symbol"
    elsif params[:ticker]
      require 'json'
      require 'net/http'

      @url = "https://cloud.iexapis.com/stable/stock/" + @api + "/quote?token=pk_90dd9d4ea08c4c30a8ee233df365eaad"
      @uri = URI(@url)
      @response = Net::HTTP.get_response(@uri)
      
      # Because this API returns shit if it cant find anything, custom error handling.
      if @response.body == "Unknown symbol"
        @error = "Stock not found, enter another symbol"
      else
        @output = JSON.parse(@response.body)
        
        # run API to get logo
        @logoUrl = "https://cloud.iexapis.com/stable/stock/" + @api + "/logo?token=pk_90dd9d4ea08c4c30a8ee233df365eaad"  
        @logoUri = URI(@logoUrl)
        @logoResponse = Net::HTTP.get(@logoUri)
        @logoOutput = JSON.parse(@logoResponse)
        
        # create varibles to send to view
        @companyName = @output['companyName']
        @symbol = @output['symbol']
        @latestPrice = @output['latestPrice']
        @changePercent = @output['changePercent']
        @primaryExchange = @output['primaryExchange']
        @logoUrlOutput = @logoOutput['url']
      end
    end
  end

  def about
  end
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  before_action :set_stock, only: [:show, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /stocks
  # GET /stocks.json
  def index
    @stocks = Stock.all
  end

  # GET /stocks/1
  # GET /stocks/1.json
  def show
  end

  # GET /stocks/new
  def new
    @stock = Stock.new
  end

  # GET /stocks/1/edit
  def edit
  end

  # POST /stocks
  # POST /stocks.json
  def create
    @stock = Stock.new(stock_params)

    respond_to do |format|
      if @stock.save
        format.html { redirect_to @stock, notice: 'Stock was successfully created.' }
        format.json { render :show, status: :created, location: @stock }
      else
        format.html { render :new }
        format.json { render json: @stock.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stocks/1
  # PATCH/PUT /stocks/1.json
  def update
    respond_to do |format|
      if @stock.update(stock_params)
        format.html { redirect_to @stock, notice: 'Stock was successfully updated.' }
        format.json { render :show, status: :ok, location: @stock }
      else
        format.html { render :edit }
        format.json { render json: @stock.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stocks/1
  # DELETE /stocks/1.json
  def destroy
    @stock.destroy
    respond_to do |format|
      format.html { redirect_to stocks_url, notice: 'Stock was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

def correct_user
  @ticker = current_user.stocks.find_by(id: params[:id])
  redirect_to stocks_path, notice: "Not Authorised to edit this stock" if @ticker.nil?
end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_stock
      @stock = Stock.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def stock_params
      params.require(:stock).permit(:ticker, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/views/home/_flash.html.erb
<br/>
<% flash.each do |name, msg| %>
    <div class="alert alert-warning" role="alert">
        <button class="close" data-dismiss="alert">
            <small><sup>x</sup></small>
        </button>
        <%= content_tag(:div, msg) %>
    </div>
<% end %>

app/views/home/_footer.html.erb
<br/>
<center><p style="font-size: 0.8em;">Data sourced from IEX Cloud</p></center>

app/views/home/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light">
    <%= link_to "Stocks", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to "About", home_about_path, class: "nav-link" %>
      </li>

      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to "Edit Profile", edit_user_registration_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Watchlist", stocks_path, class: "nav-link" %>
        </li>

      <% end %>
    </ul>
    <% if user_signed_in? %>
      <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "btn btn-info my-2 my-sm-0" %>
    <% else %>
      <%= link_to "Login", new_user_session_path, class: "btn btn-success my-2 my-sm-0" %>
      <%= link_to "Sign Up", new_user_registration_path, class: "btn btn-info my-2 my-sm-0" %>
    <% end %>
  </div>
</nav>

app/views/home/about.html.erb
<h1>About</h1>

<p>Use this site to check stock information. Sign in to create a watchlist and follow mulitple companies at once.</p>

app/views/home/index.html.erb
<center><h1><strong>Stock Checker</strong></h1></center>
            <br/>
<div class="row">
    <div class="col-md-6">
        <div class="jumbotron">
        <em>Quickly check a stock price by typing the ticker <strong>Symbol</strong></em><br/><br/>
            <%= form_tag root_path, :method => 'POST' do %>
                <%= text_field_tag 'ticker', nil, placeholder: "Enter Ticker Symbol", size: 50, class: "form-control" %>
                <br/>
                <center><%= submit_tag 'Lookup', class: "btn btn-success" %></center>
            <% end %>
        </div>
    </div>

<div class="col-md-6">
    <div class="jumbotron" id="jumbo2" style="height: 34vh;">
    <em id="headerText">Company Information:</em><br/><br/>
        <% if @nothing %>
           <%= @nothing %>     
        <% elsif @output%>
            <div class="compInfo">
                <div class="stockInfo">
                    <strong><%= @symbol %></strong><br/>    
                    <%= @companyName %><br/>   
                    <%= @latestPrice %><br/>
                    <%= @changePercent %><br/>
                    <%= @primaryExchange %><br/>
                </div>
                <div class="stockImg">
                    <img class="stockLogo" src="<%= @logoUrlOutput %>"/>
                </div>
            </div>
        <% else @error %>
            <%= @error %>
        <% end %>
        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Stock Checker</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'application', "https://fonts.googleapis.com/css?family=Raleway&display=swap" %>
  </head>

  <body>
    <%= render 'home/navbar' %>
    <div class="container">
      <%= render 'home/flash' %>

    <br/>
    <%= yield %>
    </div>
    <%= render 'home/footer' %>
  </body>
</html>

app/views/stocks/_form.html.erb
    <%= form_with(model: stock, local: true) do |form| %>
      <% if stock.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(stock.errors.count, "error") %> prohibited this stock from being saved:</h2>

          <ul>
          <% stock.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>
<br/>
      <div class="field">
        <%= form.text_field :ticker, class:"form-control", placeholder: "Enter Ticker Symbol" %>
      </div>

      <div class="field">
        <%= form.number_field :user_id, value: current_user.id, type: :hidden %>
      </div>
<br/>
      <%= submit_tag 'Add', class: "btn btn-success" %>
    <% end %>
<br/>

app/views/stocks/edit.html.erb
<div class="col-md-6 offset-md-3">
  <div class="jumbotron">
    <h1>Editing Stock</h1>

    <%= render 'form', stock: @stock %>
  </div>
<%= link_to 'Show', @stock %> |
<%= link_to 'Back', stocks_path %>
</div>

app/views/stocks/index.html.erb
 <table class="table table-striped table-hover">
    <thead class="thead">
      <tr>
        <th>Company Name</th>
        <th>Ticker</th>
        <th>Current Price</th>
        <th>Market Cap</th>
        <th>Day Change</th>
        <th colspan="1"></th>
      </tr>
    </thead>

    <tbody>
      <% @stocks.each do |stock| %>
        <% if stock.user_id == current_user.id %>
          


        <% @url = "https://cloud.iexapis.com/stable/stock/" + stock.ticker + "/quote?token=pk_90dd9d4ea08c4c30a8ee233df365eaad" %>
        <% @uri = URI(@url) %>
        <% @response = Net::HTTP.get_response(@uri) %>
        <% if @response.body == "Unknown symbol" %>
          <tr>
            <td><%= link_to "Error", stock %></td>
            <td><%= stock.ticker %></td>
            <td>N/A</td>
            <td>N/A</td>
            <td><center><%= link_to 'Edit', edit_stock_path(stock) %></center></td>
            <td><center><%= link_to 'Delete', stock, method: :delete, data: { confirm: 'Are you sure?' } %></center></td>
          </tr>
        <% else %>  
          <% @ticker = JSON.parse(@response.body) %>
          <% @price = @ticker['latest_price'] %>
    
              <tr>
                <td><%= link_to @ticker['companyName'], stock %></td>
                <td><%= @ticker['symbol'] %></td>
                <td>$<%= number_with_precision(@ticker['latestPrice'], :precision => 2, :delimiter => ',') %></%><%= @price %></td>
                <td>$<%= number_with_precision(@ticker['marketCap'], :precision => 2, :delimiter => ',')%></%></td>
                <td><%= @ticker['changePercent'] %>%</td>
                <td><center><%= link_to 'Delete', stock, method: :delete, data: { confirm: 'Are you sure?' } %></center></td>
              </tr>
        <% end %>   
        <% end %>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'Add a Stock', new_stock_path, class: "btn btn-success" %>
</div>

app/views/stocks/new.html.erb
<div class="container">
  <div class="col-md-6 offset-md-3">
    <div class="jumbotron">
      <center><h1>Add a Stock</h1></center>

      <%= render 'form', stock: @stock %>

      <%= link_to 'Back', stocks_path %>
    </div>
  </div>
</div>

app/views/stocks/show.html.erb
<div class="col-md-6 offset-md-3">
  <div class="jumbotron">
    <% @url = "https://cloud.iexapis.com/stable/stock/" + @stock.ticker + "/quote?token=pk_90dd9d4ea08c4c30a8ee233df365eaad" %>
    <% @uri = URI(@url) %>
    <% @response = Net::HTTP.get_response(@uri) %>
    <% if @response.body == "Unknown symbol" %>
        <% @error = "This symbol does not exist." %>
    <% else %>
        <% @ticker = JSON.parse(@response.body) %>
        <center><h2><strong><%= @ticker['companyName'] %></center></strong></h2>
        <center>Ticker Symbol: <%= @ticker['symbol'] %></center>
        <center>Current Price: $<%= number_with_precision(@ticker['latestPrice'], :precision => 2, :delimiter => ',')%></%></center>
        <center>Previous Close: <%= number_with_precision(@ticker['previousClose'], :precision => 2, :delimiter => ',') %></center>
        <center>YTD Change: $<%= number_with_precision(@ticker['ytdChange'], :precision => 2, :delimiter => ',')%></center>
        <center>Market Cap: $<%= number_with_precision(@ticker['marketCap'], :precision => 2, :delimiter => ',')%></%></center>
          
        <% @logoUrl = "https://cloud.iexapis.com/stable/stock/" + @stock.ticker + "/logo?token=pk_90dd9d4ea08c4c30a8ee233df365eaad" %> 
        <% @logoUri = URI(@logoUrl) %>
        <% @logoResponse = Net::HTTP.get(@logoUri) %>
        <% @logoOutput = JSON.parse(@logoResponse) %>
    <% end %>  
      <br/>
      <% if @ticker %> 
        <center><img src="<%= @logoOutput['url'] %>"/></center>
      <% else %>
        <%= @error %>
        <br/>
      <% end %>
      <br/>
      

  <%= link_to 'Back', stocks_path, class: "btn btn-info" %>
  </div>
  </div>